### PR TITLE
fixed modal bottom sheet deprecation

### PR DESCRIPTION
**Pull request by followthemoney1**
to use: 
```
 modal_bottom_sheet: #^2.1.2
    #    path: /Users/dmitrydyachenko/Desktop/modal_bottom_sheet/modal_bottom_sheet
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
```

### CODE REVIEW

**Comment by ascentman** [comment]
works for me

**Comment by fleetimee** [comment]
You're saint

**Review by fleetimee — APPROVED** [review]

**Comment by nagringapp** [comment]
It worked for me

**Comment by jamesblasco** [comment]
I have decided to rename the variable in a mayor version in order to simplify the migration proccess.

**Comment by jamesblasco** [comment]
I have decided to rename the class in a new mayor version in order to simplify the migration.
More info here: https://github.com/jamesblasco/modal_bottom_sheet/issues/325

**Comment by mobilsoylu** [comment]
works for me. Thanks ✌🏼

**Comment by nagringapp** [comment]
Is there any new version up?

**Pull request closed without merging**
