### PR TITLE
fix: hide flutter imports

### PR DESCRIPTION
**Pull request by netos23**
in the latest release, the flutter team added its ModalBottomSheetRoute to the public api and an import conflict arose. These changes hide the import of the flutter.

### CODE REVIEW

**Comment by OrgilTs** [comment]
yeah i do it lol

**Review by nohli — APPROVED** [review]

**Comment by nohli** [comment]
Thanks for the fix! Could also be renamed instead of hidden.

@jamesblasco would be great to merge and publish this soon, as the latest Flutter stable doesn't build any more with this package. There is possibly one more issue:

Screenshot 2023-01-25 at 18 04 25

**Comment by netos23** [comment]
> Thanks for the fix! Could also be renamed instead of hidden.
> 
> @jamesblasco would be great to merge and publish this soon, as the latest Flutter stable doesn't build any more with this package. There is possibly one more issue:
> 
> Screenshot 2023-01-25 at 18 04 25

I agree that renaming it is a better solution to the problem, but it will have a negative effect on support.  We have about 20 projects in our company that depend on this package.  Hiding the import will save some time.

**Comment by samnbd** [comment]
waiting for this to be released, because it's blocking the build of apps with Flutter 3.7.0

**Review by TjarcoKerssens — APPROVED** [review]

**Comment by netos23** [comment]
I also fixed some analyzer issues

**Comment by nohli** [comment]
> Thanks for the fix! Could also be renamed instead of hidden.
> 
> 
> 
> @jamesblasco would be great to merge and publish this soon, as the latest Flutter stable doesn't build any more with this package. There is possibly one more issue:
> 
> 
> 
> Screenshot 2023-01-25 at 18 04 25
> 
> 
> 
> 

What about the second build issue (Object/Future)? Does it also need to be fixed?

**Comment by netos23** [comment]
> > Thanks for the fix! Could also be renamed instead of hidden.
> > @jamesblasco would be great to merge and publish this soon, as the latest Flutter stable doesn't build any more with this package. There is possibly one more issue:
> > Screenshot 2023-01-25 at 18 04 25
> 
> What about the second build issue (Object/Future)? Does it also need to be fixed?

The problem with Object/Future is a consequence of the fact that an import error occurred.

**Pull request closed without merging**
