### PR TITLE
Hero Support

### PR DESCRIPTION
**Pull request by jamesblasco**

### CODE REVIEW

**Comment by appinteractive** [comment]
Any progress? @jamesblasco

**Comment by ERICAntoine** [comment]
Any progress? @jamesblasco

**Comment by aliazxs** [comment]
any update?

**Comment by sdegenaar** [comment]
Any progress?

**Comment by MindMayhem** [comment]
check this

https://github.com/jamesblasco/modal_bottom_sheet/pull/213

**Comment by raulmabe** [comment]
This feature would be so awesome! I hope the #213 gets merged

**Comment by MindMayhem** [comment]
> This feature would be so awesome! I hope the #213 gets merged

U can easily edit source code of this package by pressing Ctrl+Right Mouse on showMaterialBottomSheet -> ModalBottomSheet -> ModalBottomSheetRoute and then just edit class like in my pull request

This package unmaintained now, as i think, so, no one will merge my pull request

Also, at the moment i'm making my own alternative to this package with cupertinostyle animations and gestures, so, just wait for it, if you interested, of course

**Comment by DieGlueckswurst** [comment]
@MindMayhem  any news on this?

**Comment by adnandrops** [comment]
This will be so dope once implemented, I can’t wait.
Do we have any news?

**Comment by jamesblasco** [comment]
Now the route is a PageRoute that supports Hero animations

**Comment by WhiteSnowGirl** [comment]
AND， SO it's work？

**Pull request closed without merging**
