### PR TITLE
Add bottom modal scroll physics

### PR DESCRIPTION
**Pull request by jamesblasco**

### CODE REVIEW

**Comment by NaikSoftware** [comment]
Why not merged?)

**Comment by sebastienwozny** [comment]
Any news? I definitely need it!

**Comment by otopba** [comment]
This is an awesome update!

**Comment by jamesblasco** [comment]
I won't merge this PR at the end. In the upcoming weeks a new package will be released that has this implemented by default

**Comment by kvenn** [comment]
Which package is that?

**Comment by LeeSeongJinCa** [comment]
I think this is the package: https://github.com/jamesblasco/modal_bottom_sheet/tree/main/sheet

**Pull request closed without merging**
