### PR TITLE
Hero animation support

### PR DESCRIPTION
**Pull request by MindMayhem**
Simple solution to work Hero animation with modal_bottom_sheet

### CODE REVIEW

**Comment by GaeDLLD** [comment]
It's works perfectly, many thanks @MindMayhem !!!
Hope it will be merged on main soon...

**Comment by akki01133** [comment]
hero animation is not working in my app. is anything different needed to be done ? @jamesblasco  @MindMayhem  @GaeDLLD

**Comment by MindMayhem** [comment]
> hero animation is not working in my app. is anything different needed to be done ? @jamesblasco @MindMayhem @GaeDLLD

check for tags in hero's widgets, they should be equal on both screens

**Comment by akki01133** [comment]
> 

yeah working now I thanx!!

**Pull request merged**
