### PR TITLE
Add PointerDeviceKind to VelocityTracker()

### LINKED ISSUE #72: VelocityTracker() needs a positional argument in bottom_sheet.dart
Ola @jamesblasco ,

Thank you so much for this package I love this package. But, IDK why i got this error -

```console
[+4385 ms] ../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:295:43: Error: Too few positional
arguments: 1 required, 0 given.
[   +1 ms]         _velocityTracker = VelocityTracker();
[        ]                                           ^
[        ] /C:/src/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't match.
[        ]   VelocityTracker(this.kind);
[        ]   ^^^^^^^^^^^^^^^
[+9204 ms] [+13567 ms] ../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.2.0+1/lib/src/bottom_sheet.dart:295:43: Error: Too few
positional arguments: 1 required, 0 given.
[  +12 ms] [   +3 ms]         _velocityTracker = VelocityTracker();
[   +2 ms] [        ]                                           ^
[        ] [        ] /C:/src/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart:152:3: Context: Found this candidate, but the arguments don't
match.
[   +1 ms] [        ]   VelocityTracker(this.kind);
[        ] [        ]   ^^^^^^^^^^^^^^^
```
I have found this issue recently, it works fine before(15 days ago), I even made app build. and as it expecting positional arguments I have a solution for it. and lemme make a PR if possible. It gives a quick fix  :wink:

regards

### PR DESCRIPTION
**Pull request by yahu1031**
Ola @jamesblasco ,

As I have mentioned in #72 I have made a fix and please do verify it and pull ASAP, cause I need to build my app, It takes large size 😜.

Regards.

Closes #72

### CODE REVIEW

**Comment by jamesblasco** [comment]
I have some concers as windows devices have touch screens too. I am asking because I think VelocityTracker does not depend on the input kind to calculate the velocity. Therefore we don't have to programmatically add it ourselves.

Feel free to use this PR in your project pubspec.

This change is not in the stable version of Flutter

**Comment by yahu1031** [comment]
@jamesblasco yes of course but as the windows main feature is all about mouse velocity we can ignore that if I'm not wrong.

**Comment by yahu1031** [comment]
Or we can make it unknown for all other devices other than smartphones😅

**Comment by yahu1031** [comment]
Ola @jamesblasco 

Just give it a try using my git repo and check if it works or not because we have declared particular devices. If still you are bothered about your [concern](https://github.com/jamesblasco/modal_bottom_sheet/pull/73#issuecomment-691699589), we even have some smartphone devices which use mice. so and some Ipads have stylus. so we can't keep doing that for each and every device. For that we must deep dive into `pointer.dart` and then we must add some more features. Hope you will give a try.
If this works I have made a pull request please do check that out 😉.

Regards.

**Comment by cpboyd** [comment]
The flutter change: https://github.com/flutter/flutter/commit/29898812d476051c750ae8979e1ad8e212a00f29

@jamesblasco We could simply use `PointerDeviceKind.unknown` (which is at the moment equivalent to `PointerDeviceKind.touch`) as a hotfix.

I imagine the change was primarily made to better respect `slop` with more precise inputs like `mouse` and `stylus`.

Apple kind of blew up this issue with their immediate iOS 14 release, as it pushed the Flutter team to rapidly roll-out a release to beta (and presumably stable soon).

**Comment by jamesblasco** [comment]
Thanks @yahu1031 
I have changed the code to use TargetPlatform instead of Platform as this last one is not usable in Flutter web.

**Comment by yahu1031** [comment]
@jamesblasco thanks bud 😉

**Pull request merged**
