### PR TITLE
CupertinoUserInterfaceLevel and ColorFilter for CupertinoBottomSheet

### PR DESCRIPTION
**Pull request by bierbaumtim**
This PR adds the changes discussed in #41 .

The previousRoute is now wrapped with a ColorFilter and has a `CupertinoUserInterfaceLevel.elevated` thus the `CupertinoDynamicColors` automatically uses the elevatedColor. This makes it unnecessary to detect if dark mode is activated.
The changes are only applied when the transition is started. While making the changes I noticed that even when the animation isn't started the child is wrapped with Translate and ClipRect. This is not nessecary and therefore I adding a check if the animation.value is 0 then only the child itself is displayed and otherwise the widgets nessecary for the translation. This should improve the performance a bit.

The seconds change I made was to wrap the child of the modal with CupertinoUserInterfaceLevel and give it also an `CupertinoUserInterfaceLevel.elevated` .

### CODE REVIEW

**Comment by bierbaumtim** [comment]
While working on it I also have issues with using dart language features like extension methods and collection-if. I always get an error that I have to enable the experiments but that does not work. Since I did not have such issues with all my other projects the project might be corrupted.

**Comment by jamesblasco** [comment]
Thanks for the PR and all the research. I will take a look at this as soon as I can
It would be interesting to have a dark mode example of this too

**Comment by bierbaumtim** [comment]
Yeah, will use the changes on a beta version of a production app, to get some feedback from the users.

Also I could adding a second example of an CupertinoApp to show it in Darkmode. The current example would not work perfectly, because material and Cupertino widget mixed and colors are hard coded.

**Comment by bierbaumtim** [comment]
@jamesblasco Should we split the example into material example and Cupertino example or duplicate each example and adjust them for cupertino?

**Comment by jamesblasco** [comment]
Mmm I prefer the second option, maybe we don't need to duplicate all of them, but just some to prove dark/light mode no?
Could we nested a CupertinoApp inside a MaterialApp no?

**Comment by bierbaumtim** [comment]
Ok, I'm gonna duplicate all cupertino implementations. But nesting CupertinoApp and MaterialApp isn't a good solution in my opinnion, because most of the time it causes theming issues.

I prefer to split up the example because the Cupertino modal sheets and widgets are designed to work perfectly in CupertinoApp and the material ones works perfectly in MaterialApp. And I think that the developer assumes that the widgets with cupertino in the name works only with cupertino and material widgets only with Material, just like the flutter widgets do.

Also I would duplicate all custom modal sheets which works with both cupertino and material.

What do you think about it?

**Comment by bierbaumtim** [comment]
Also I found a issue in the ColorFilter for the previous route, so I have to do a bit more work to make it look like native. Maybe we should expose the color, because on iOS I found some apps which uses custom colors it.

**Comment by jamesblasco** [comment]
Have you managed to solve it?

**Comment by bierbaumtim** [comment]
I've partially solved it.
The problem is that on iOS, if a modal route is pushed the background color of the previous route is animated from the base color to the elevated color. But after I looked into more built-in iOS apps I can't see the default behaviour and since I don`t have an mac I can`t build an simple iOS app to see the default behaviour
I also can't find a way to implement the animation of the backgroundColor. So for now the previousRoute uses the base color and the ColorFilter the elevatedColor. It is not the perfect solution.

**Comment by bierbaumtim** [comment]
But I finished the cupertino example app. It contains every example as the material app. Half of the examples are now duplicated to add cupertino support. All others gets small changes to show properly in the cupertino example app.

**Comment by jamesblasco** [comment]
Awesome, I will review it all tomorrow.  Tbh there is not much information from Apple inside the human design guidelines.
The modal available for developers do what you describe there, but Apple implements it differently in some of their native apps, 🤷🏻‍♂️

**Comment by bierbaumtim** [comment]
I managed it to animate the backgroundColor of the previousRoute by wrapping it with a CupertinoTheme. But the navigationBar not using the right color and I need more time to figure out how to solve it.
But I think first we should finish this PR and than do some improvements.

**Comment by jamesblasco** [comment]
Hello @bierbaumtim! I haven't forgotten about this PR but now I am working to merge a new API similar to this package inside the flutter framework. This code will also be part of that. 
If you are interested you can take a look at the draft here 🙂
https://github.com/flutter/flutter/pull/67515#issuecomment-719198013

**Comment by bierbaumtim** [comment]
I saw that you're working on integrating this feature into flutter itself but did not follow along the conversation in the PR. I've now looked into again it looks really good and i am looking forward to see this in one of the next version of flutter.

**Comment by bierbaumtim** [comment]
Closing this PR and will open new ones based on the latest version on master. 
I will open a PR for the changes on CupertinoBottomSheet and one for the darkmode support for the example.
This one contains to much changes for different issues which makes it difficult to merge it fast and ensure good quality.

**Pull request closed without merging**
